# Generated by Django 6.0.6 on 2026-06-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('viewer', 'Viewer'), ('data_enumerator', 'Data Enumerator'), ('field_coordinator', 'Field Coordinator')], default='viewer', max_length=50),
        ),
    ]
