# Generated by Django 6.0.6 on 2026-06-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('viewer', 'Viewer'), ('data_enumerator', 'Data Enumerator'), ('field_coordinator', 'Field Coordinator')], db_index=True, default='viewer', max_length=50),
        ),
    ]
