# Generated by Django 6.0.6 on 2026-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_control',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
