# Generated by Django 5.1.7 on 2026-06-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='file',
        ),
        migrations.AddField(
            model_name='assessment',
            name='excel',
            field=models.FileField(blank=True, null=True, upload_to='assessment/excel/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='assessment/pdf/'),
        ),
    ]
