# Generated by Django 6.0.6 on 2026-06-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assessment_file_assessment_excel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_survey', models.CharField(max_length=255)),
                ('level_of_survey', models.CharField(max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_survey_tool', models.TextField(blank=True, null=True)),
                ('last_survey_conducted', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
