# Generated by Django 6.0.6 on 2026-06-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessmentanalytics_assessmentstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentAnalytics',
        ),
    ]
