# Generated by Django 6.0.6 on 2026-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_assessment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
