# Generated by Django 6.0.6 on 2026-06-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
    ]
