# Generated by Django 6.0.6 on 2026-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minute', '0003_meetingminute_uploaded_by_meetingminute_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingminute',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], db_index=True, default='unverified', max_length=20),
        ),
    ]
