# Generated by Django 6.0.6 on 2026-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minute', '0004_alter_meetingminute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingminute',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingminute',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('returned', 'Returned')], db_index=True, default='unverified', max_length=20),
        ),
    ]
