# Generated by Django 6.0.6 on 2026-06-30 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_minute', '0005_meetingminute_comment_alter_meetingminute_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingminute',
            name='comment',
        ),
        migrations.CreateModel(
            name='MeetingMinuteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_minute_comments', to=settings.AUTH_USER_MODEL)),
                ('meeting_minute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meeting_minute.meetingminute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
