# Generated by Django 6.0.6 on 2026-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_mapcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
