# Generated by Django 6.0.6 on 2026-06-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_mapcategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='file',
            new_name='image',
        ),
    ]
