# Generated by Django 6.0.6 on 2026-07-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('agency', models.CharField(max_length=255)),
                ('compound_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('province', models.CharField(max_length=255)),
                ('area_council', models.CharField(max_length=255)),
                ('island', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('compound_function', models.CharField(blank=True, max_length=255, null=True)),
                ('is_ec_owner_approved', models.BooleanField(default=False)),
                ('is_ec_govt_approved', models.BooleanField(default=False)),
                ('name_of_outside_temporary_shelter', models.CharField(blank=True, max_length=255, null=True)),
                ('outside_temporary_shelter_capacity', models.IntegerField(blank=True, null=True)),
                ('first_aid_kit_availability', models.BooleanField(default=False)),
                ('first_aid_trained_person', models.BooleanField(default=False)),
                ('electricity_source', models.CharField(blank=True, max_length=255, null=True)),
                ('drinking_water_source', models.CharField(blank=True, max_length=255, null=True)),
                ('washing_water_source', models.CharField(blank=True, max_length=255, null=True)),
                ('water_storage_capacity_litres', models.IntegerField(blank=True, null=True)),
                ('no_of_buildings', models.IntegerField(blank=True, null=True)),
                ('no_of_rooms', models.IntegerField(blank=True, null=True)),
                ('internal_building_evacuee_capacity', models.IntegerField(blank=True, null=True)),
                ('disaster_suitable_for', models.CharField(blank=True, max_length=255, null=True)),
                ('enginerring_certified_cyclone_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('total_mens_toilet', models.IntegerField(blank=True, null=True)),
                ('total_womens_toilet', models.IntegerField(blank=True, null=True)),
                ('total_unisex_toilet', models.IntegerField(blank=True, null=True)),
                ('total_disability_access_toilet', models.IntegerField(blank=True, null=True)),
                ('total_mens_shower', models.IntegerField(blank=True, null=True)),
                ('total_womens_shower', models.IntegerField(blank=True, null=True)),
                ('total_unisex_shower', models.IntegerField(blank=True, null=True)),
                ('total_disability_access_shower', models.IntegerField(blank=True, null=True)),
                ('kitchen_cooking_facilities', models.BooleanField(default=False)),
                ('laundry_facilities', models.BooleanField(default=False)),
                ('communication_back_up', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['compound_name'], name='evacutation_compoun_59af64_idx'), models.Index(fields=['latitude', 'longitude'], name='evacutation_latitud_e1243a_idx')],
            },
        ),
    ]
