# Generated by Django 6.0.6 on 2026-07-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_centre', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evacuationcentre',
            new_name='evacuation__compoun_c0bce6_idx',
            old_name='evacutation_compoun_59af64_idx',
        ),
        migrations.RenameIndex(
            model_name='evacuationcentre',
            new_name='evacuation__latitud_052a05_idx',
            old_name='evacutation_latitud_e1243a_idx',
        ),
    ]
