# Generated by Django 6.0.6 on 2026-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_centre', '0003_evacuationcentreimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcentreimport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
