# Generated by Django 6.0.6 on 2026-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Displacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_code', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('operation', models.CharField(max_length=100)),
                ('admin0_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin0_pcode', models.CharField(blank=True, max_length=100, null=True)),
                ('admin1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin1_pcode', models.CharField(blank=True, max_length=100, null=True)),
                ('admin2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin2_pcode', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_code', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_level', models.IntegerField(blank=True, null=True)),
                ('num_present_idps', models.IntegerField(blank=True, null=True)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('reporting_year', models.IntegerField(blank=True, null=True)),
                ('reporting_month', models.IntegerField(blank=True, null=True)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('displacement_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('males_number', models.IntegerField(blank=True, null=True)),
                ('female_number', models.IntegerField(blank=True, null=True)),
                ('males_number_0_4', models.IntegerField(blank=True, null=True)),
                ('females_number_0_4', models.IntegerField(blank=True, null=True)),
                ('males_number_5_17', models.IntegerField(blank=True, null=True)),
                ('females_number_5_17', models.IntegerField(blank=True, null=True)),
                ('males_number_18_59', models.IntegerField(blank=True, null=True)),
                ('females_number_18_59', models.IntegerField(blank=True, null=True)),
                ('males_number_60_plus', models.IntegerField(blank=True, null=True)),
                ('females_number_60_plus', models.IntegerField(blank=True, null=True)),
                ('total_vul_hhs', models.IntegerField(blank=True, null=True)),
                ('idp_origin_admin1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('idp_origin_admin1_pcode', models.CharField(blank=True, max_length=100, null=True)),
                ('assessment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=255, null=True)),
                ('idp_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('idp_destination_admin1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('idp_destination_admin1_pcode', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['operation'], name='displacemen_operati_7d3c16_idx'), models.Index(fields=['admin1_name'], name='displacemen_admin1__9db617_idx'), models.Index(fields=['admin2_name'], name='displacemen_admin2__353efe_idx'), models.Index(fields=['displacement_reason'], name='displacemen_displac_ca178c_idx'), models.Index(fields=['reporting_date'], name='displacemen_reporti_fb30cf_idx')],
            },
        ),
    ]
