# Generated by Django 6.0.6 on 2026-07-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displacement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displacement',
            options={'verbose_name': 'Displacement', 'verbose_name_plural': 'Displacement'},
        ),
        migrations.RemoveField(
            model_name='displacement',
            name='admin_code',
        ),
    ]
