# Generated by Django 5.1.7 on 2026-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('link', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emergency Alert',
                'verbose_name_plural': 'Emergency Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='emergency_a_created_5e0c69_idx')],
            },
        ),
    ]
