# Generated by Django 5.1.7 on 2026-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_alert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
