# Generated by Django 6.0.6 on 2026-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_date_report_type_report_url_alter_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_situation_report',
            field=models.BooleanField(default=False),
        ),
    ]
