# Generated by Django 6.0.6 on 2026-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_status_report_uploaded_by_report_verified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
