# Generated by Django 6.0.6 on 2026-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_idp', models.IntegerField(default=0)),
                ('evacuation_centres', models.IntegerField(default=0)),
                ('affected_hhs', models.IntegerField(default=0)),
                ('villages_assessed', models.IntegerField(default=0)),
                ('shelter_needs', models.IntegerField(default=0)),
                ('access_to_basic_services', models.IntegerField(default=0)),
                ('children_affected', models.IntegerField(default=0)),
                ('person_with_disabilities', models.IntegerField(default=0)),
                ('active_partners', models.IntegerField(default=0)),
                ('response_coverage', models.IntegerField(default=0)),
            ],
        ),
    ]
