# Generated by Django 6.0.6 on 2026-07-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_evacuationcentresummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('impact', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceSectorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.FloatField(default=0)),
            ],
        ),
    ]
