# Generated by Django 6.0.6 on 2026-07-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_historicalevents_provincesectorsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCentreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='EvacuationCentreSummary',
            new_name='EvacuationCentreLocationSummary',
        ),
    ]
