# Generated by Django 6.0.6 on 2026-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_evacuationcentrelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evacuationcentrelist",
            name="hhs",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evacuationcentrelist",
            name="status",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evacuationcentrelist",
            name="type",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evacuationcentrelist",
            name="site_name",
            field=models.CharField(max_length=100),
        ),
    ]
