# Generated by Django 6.0.6 on 2026-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_evacuationcentrelist_hhs_evacuationcentrelist_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evacuationcentrelist',
            name='hhs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
