# Generated by Django 6.0.6 on 2026-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_evacuationcentrelist_hhs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTrackingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('partner', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('coverage', models.FloatField(default=0)),
            ],
        ),
    ]
