# Generated by Django 6.0.6 on 2026-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_banner_powerbiiframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbiiframe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
