# Generated by Django 5.1.7 on 2026-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_powerbiiframe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='historical_events'),
        ),
        migrations.AddField(
            model_name='powerbiiframe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='power_bi_iframe'),
        ),
    ]
