# Generated by Django 5.1.7 on 2026-08-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('survery_tools', models.TextField(blank=True, null=True)),
                ('level', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='archive/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='archive_arc_created_9c640f_idx'), models.Index(fields=['survey_type'], name='archive_arc_survey__a61260_idx'), models.Index(fields=['level'], name='archive_arc_level_02aecc_idx')],
            },
        ),
    ]
