# Generated by Django 6.0.6 on 2026-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest_update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestupdate',
            name='thumbnail_alt_desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thumbnail Alt Description'),
        ),
    ]
