# Generated by Django 6.0.6 on 2026-06-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop',
            name='is_admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
