# Generated by Django 6.0.6 on 2026-06-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop', '0002_sop_is_admin_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sop'),
        ),
    ]
