# Generated by Django 6.0.6 on 2026-06-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='type',
            field=models.CharField(choices=[('National Co-lead', 'National Co-lead'), ('Sub-National', 'Sub-National'), ('Inter-Cluster', 'Inter-Cluster')], db_index=True, default='', max_length=255),
        ),
    ]
